import Provider from './Provider'
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
  session:any
}) {
  return (
    <html lang="en">
      <Provider>
        <body>{children}</body>
      </Provider>
      
    </html>
  )
}
