import React from 'react'
// import Provider from './Provider'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode,
  session:any
}) {
  return (
    <html lang='es'>
      {/* <Provider> */}

      <body className='min-h-screen flex flex-col'>
        <Header />
        <main className='flex-grow container mx-auto px-4 sm:px-6'>
          {children}
        </main>
        <Footer />
      </body>
      {/* </Provider> */}

    </html>
  )
}
