import React from 'react'
// import Provider from './Provider'
import './../styles/globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export default function RootLayout ({
  children
}: {
  children: React.ReactNode,
  session:any
}) {
  return (
    <html lang='es'>
      <head>
        <title>Blog for dev</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='./favicon' />
      </head>
      {/* <Provider> */}

      <body>
        <div className='min-h-screen flex flex-col'>
          <Header />
          <main className='flex-grow container mx-auto px-4 sm:px-6'>
            {children}
          </main>
          <Footer />
        </div>
      </body>
      {/* </Provider> */}

    </html>
  )
}
